import type { Metadata } from 'next'
import poster from './_media/poster'
import video1 from './_media/video1'
import video2 from './_media/video2'
import video3 from './_media/video3'
import cinema1 from './_media/cinema1'
import cinema2 from './_media/cinema2'

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://editoralevi.com.br'
const pageUrl = `${siteUrl}/a-prisao-ou-o-milhao`

export const metadata: Metadata = {
  title: 'A Prisão ou o Milhão — Adilson Borges',
  description: 'A Prisão ou o Milhão, de Adilson Borges. Uma história real de queda, escolhas e reconstrução. Prefácio de Dr. Augusto Cury.',
  alternates: { canonical: '/a-prisao-ou-o-milhao' },
}

const VIDEO_DATA = `data:video/mp4;base64,${video1}${video2}${video3}`
const POSTER_DATA = `data:image/jpeg;base64,${poster}`
const CINEMA_DATA = `data:image/jpeg;base64,${cinema1}${cinema2}`

const bookSchema = {
  '@context': 'https://schema.org',
  '@type': 'Book',
  name: 'A Prisão ou o Milhão',
  url: pageUrl,
  isbn: '9786501430751',
  inLanguage: 'pt-BR',
  author: { '@type': 'Person', name: 'Adilson Borges' },
  publisher: { '@type': 'Organization', name: 'Editora Levi', url: siteUrl },
}

const pageStyles = `
body:has(.book-v2-html) .site-header,
body:has(.book-v2-html) .footer { display: none !important; }
body:has(.book-v2-html) main { overflow: hidden; }

:root{--ink:#090806;--paper:#f2eee5;--gold:#c88b16;--gold2:#e6ad38;--white:#f8f4ec}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--ink);color:var(--white);font-family:Arial,Helvetica,sans-serif;overflow-x:hidden}.wrap{max-width:1240px;margin:auto;padding:0 56px}.eyebrow{letter-spacing:.18em;text-transform:uppercase;font-size:12px;font-weight:800}.btn{display:inline-flex;align-items:center;justify-content:center;padding:16px 24px;border-radius:999px;background:linear-gradient(180deg,var(--gold2),var(--gold));color:#12100d;text-decoration:none;font-weight:900;font-size:13px;letter-spacing:.04em;box-shadow:0 14px 40px rgba(200,139,22,.22)}.btn:after{content:'→';margin-left:12px;font-size:17px}

.book-hero{position:relative;isolation:isolate;display:flex;min-height:100svh;overflow:hidden;background:#090806;align-items:center}.book-hero__video,.book-hero__poster,.book-hero__wash,.book-hero__vignette{position:absolute;inset:0;width:100%;height:100%}.book-hero__poster{z-index:-4;object-fit:cover}.book-hero__video{z-index:-3;object-fit:cover;opacity:.34}.book-hero__wash{z-index:-2;background:linear-gradient(90deg,rgba(5,4,3,.98) 0%,rgba(5,4,3,.87) 30%,rgba(5,4,3,.38) 58%,rgba(5,4,3,.08) 100%)}.book-hero__vignette{z-index:-1;background:linear-gradient(0deg,rgba(5,4,3,.68),transparent 28%,rgba(5,4,3,.2))}.book-hero__content{width:min(50%,650px);margin-left:clamp(2rem,8vw,9rem);padding:clamp(3rem,7vh,5rem) 0}.book-hero__eyebrow{margin:0 0 1.35rem;color:var(--gold2);font:600 .7rem/1.2 Arial,Helvetica,sans-serif;letter-spacing:.2em;text-transform:uppercase}.book-hero__title{display:flex;flex-direction:column;gap:0;margin:0;color:var(--white);font:600 clamp(3.5rem,6.6vw,6.9rem)/.82 Georgia,'Times New Roman',serif;letter-spacing:-.055em;text-wrap:balance}.book-hero__title span:last-child{color:var(--gold2)}.book-hero__lead{max-width:28rem;margin:1.7rem 0 .7rem;color:var(--white);font:500 clamp(1.15rem,1.6vw,1.55rem)/1.15 Georgia,'Times New Roman',serif}.book-hero__description{max-width:25rem;margin:0;color:#d7d1c5;font:400 .9rem/1.55 Arial,Helvetica,sans-serif}.book-hero__action{display:flex;align-items:flex-start;gap:.9rem;margin-top:1.75rem;flex-direction:column}.book-hero__cta{display:inline-flex;min-height:3.05rem;align-items:center;justify-content:center;border-radius:999px;padding:0 1.65rem;background:var(--gold);color:#090806;font:700 .72rem/1 Arial,Helvetica,sans-serif;letter-spacing:.08em;text-decoration:none;transition:background .2s,transform .2s}.book-hero__cta:hover{background:var(--gold2);transform:translateY(-2px)}.book-hero__microcopy{color:#d7d1c5;font:400 .72rem/1 Arial,Helvetica,sans-serif}.book-hero__signature{position:absolute;right:clamp(2rem,5vw,5rem);bottom:2rem;margin:0;color:rgba(248,244,236,.62);font:400 .72rem/1 Arial,Helvetica,sans-serif;letter-spacing:.08em}

.light{background:var(--paper);color:#17130e}.statement{padding:118px 0 110px}.statement .grid{display:grid;grid-template-columns:1.1fr .9fr;gap:90px;align-items:end}.statement h2{font-family:Georgia,'Times New Roman',serif;font-size:64px;line-height:1.04;letter-spacing:-.035em;margin:0}.statement h2 em{font-style:normal;color:var(--gold)}.statement .copy{font-size:18px;line-height:1.72;color:#40392f}.statement .question{font-family:Georgia,'Times New Roman',serif;font-weight:bold;font-size:31px;line-height:1.22;margin:30px 0 30px;color:#19140d}.statement .eyebrow{color:#8c641d;margin-bottom:25px}
.cinema{height:560px;position:relative;overflow:hidden;background:#100b07}.cinema img{position:absolute;inset:-10%;width:120%;height:120%;object-fit:cover;object-position:center 62%;filter:brightness(.42) saturate(.78) blur(.2px)}.cinema:after{content:'';position:absolute;inset:0;background:linear-gradient(90deg,rgba(5,4,3,.84),rgba(5,4,3,.36),rgba(5,4,3,.78)),linear-gradient(0deg,rgba(5,4,3,.7),transparent 46%,rgba(5,4,3,.34))}.cinema .wrap{position:relative;z-index:2;height:100%;display:flex;align-items:center;justify-content:center;text-align:center}.cinema blockquote{font-family:Georgia,'Times New Roman',serif;font-size:44px;line-height:1.13;max-width:910px;margin:0}.cinema blockquote strong{color:var(--gold2);font-weight:normal}
.cury{background:radial-gradient(circle at 12% 65%,rgba(203,139,23,.18),transparent 32%),#070604;padding:120px 0;position:relative;overflow:hidden}.cury .grid{display:grid;grid-template-columns:1.05fr .95fr;gap:80px;align-items:center}.cury .eyebrow{color:var(--gold2);margin-bottom:24px}.cury h2{font-family:Georgia,'Times New Roman',serif;font-size:62px;line-height:1.02;margin:0 0 28px;letter-spacing:-.035em}.cury .body{color:#d3ccbf;font-size:17px;line-height:1.7;max-width:650px}.cury .quote{margin-top:34px;border-left:2px solid var(--gold);padding-left:24px;font-family:Georgia,'Times New Roman',serif;font-size:27px;line-height:1.35;color:#fff6e7}.cury .sig{margin-top:16px;color:#c9a76a;font-size:12px;letter-spacing:.08em;text-transform:uppercase}.portrait{height:620px;border-radius:6px;overflow:hidden;position:relative;background:radial-gradient(circle at 65% 25%,#594520 0,#24170b 36%,#0b0805 72%);border:1px solid rgba(230,173,56,.24);box-shadow:0 28px 90px rgba(0,0,0,.4)}.portrait .remote{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:center 20%;filter:grayscale(1) sepia(.18) contrast(1.03);opacity:.9}.portrait .fallback{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-family:Georgia,'Times New Roman',serif;font-size:140px;color:rgba(230,173,56,.19);letter-spacing:-.08em}.portrait:after{content:'';position:absolute;inset:0;background:linear-gradient(0deg,rgba(7,6,4,.88),transparent 58%),linear-gradient(90deg,rgba(7,6,4,.42),transparent 45%)}.portrait-label{position:absolute;z-index:3;left:28px;bottom:28px}.portrait-label strong{display:block;font-family:Georgia,'Times New Roman',serif;font-size:29px}.portrait-label span{display:block;color:#d3b978;font-size:11px;letter-spacing:.14em;text-transform:uppercase;margin-top:6px}
.identify{padding:118px 0 128px;background:linear-gradient(180deg,#f3efe7,#ece5d8);color:#17130e}.identify .top{display:grid;grid-template-columns:1.2fr .8fr;gap:90px;align-items:end;margin-bottom:54px}.identify .eyebrow{color:#8d651f;margin-bottom:22px}.identify h2{font-family:Georgia,'Times New Roman',serif;font-size:66px;line-height:1.02;margin:0;letter-spacing:-.035em}.identify .intro{font-size:17px;line-height:1.7;color:#494136}.cards{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.card{min-height:210px;padding:30px;border:1px solid #d3c8b6;background:rgba(255,255,255,.58);position:relative;overflow:hidden}.card .n{font-size:70px;font-weight:900;letter-spacing:-.08em;color:rgba(185,128,22,.18);position:absolute;right:18px;top:6px}.card p{font-family:Georgia,'Times New Roman',serif;font-size:25px;line-height:1.25;max-width:80%;margin:70px 0 0}.identify .closing{display:flex;align-items:center;justify-content:space-between;gap:40px;margin-top:46px;padding-top:34px;border-top:1px solid #d2c5b1}.identify .closing h3{font-family:Georgia,'Times New Roman',serif;font-size:38px;line-height:1.08;margin:0;max-width:780px}.identify .closing h3 span{color:#a66e0c}
@media(max-width:900px){.wrap{padding:0 24px}.statement{padding:80px 0}.statement .grid,.cury .grid,.identify .top{grid-template-columns:1fr;gap:34px}.statement h2,.cury h2,.identify h2{font-size:43px}.statement .copy{font-size:16px}.statement .question{font-size:27px}.cinema{height:480px}.cinema blockquote{font-size:34px}.cury{padding:82px 0}.cury .grid{display:flex;flex-direction:column-reverse}.portrait{width:100%;height:470px}.cury .quote{font-size:24px}.identify{padding:80px 0 86px}.cards{grid-template-columns:1fr}.card p{font-size:23px;max-width:88%}.identify .closing{align-items:flex-start;flex-direction:column}.identify .closing h3{font-size:33px}}
@media(max-width:767px){.book-hero{min-height:100svh;align-items:flex-start}.book-hero__poster,.book-hero__video{object-position:61% 50%}.book-hero__video{opacity:.22}.book-hero__wash{background:linear-gradient(180deg,rgba(5,4,3,.86) 0%,rgba(5,4,3,.52) 34%,rgba(5,4,3,.1) 59%,rgba(5,4,3,.8) 100%)}.book-hero__vignette{background:linear-gradient(0deg,rgba(5,4,3,.8),transparent 38%)}.book-hero__content{width:100%;margin:0;padding:2.3rem 1.35rem 1.5rem}.book-hero__eyebrow{margin-bottom:1.1rem;font-size:.61rem;letter-spacing:.14em}.book-hero__title{font-size:clamp(3.55rem,16vw,5rem);line-height:.82}.book-hero__lead{max-width:17rem;margin-top:1.3rem;font-size:1.2rem}.book-hero__description{max-width:18rem;font-size:.78rem;line-height:1.4}.book-hero__action{margin-top:1.25rem;gap:.7rem}.book-hero__cta{width:min(100%,18rem);min-height:3.25rem;padding:0 1rem;font-size:.66rem}.book-hero__signature{display:none}}
@media(prefers-reduced-motion:reduce){.book-hero__video{display:none}.book-hero__cta{transition:none}}
`

export default function BookLandingV2() {
  return (
    <div className="book-v2-html">
      <style dangerouslySetInnerHTML={{ __html: pageStyles }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(bookSchema) }} />
      <section className="book-hero" id="top">
        <img className="book-hero__poster" src={POSTER_DATA} alt="" aria-hidden="true" />
        <video className="book-hero__video" autoPlay muted loop playsInline preload="metadata" poster={POSTER_DATA} aria-hidden="true"><source src={VIDEO_DATA} type="video/mp4" /></video>
        <div className="book-hero__wash" aria-hidden="true" /><div className="book-hero__vignette" aria-hidden="true" />
        <div className="book-hero__content"><p className="book-hero__eyebrow">PREFÁCIO DE DR. AUGUSTO CURY</p><h1 className="book-hero__title"><span>A PRISÃO</span><span>OU O MILHÃO</span></h1><p className="book-hero__lead">Um livro escrito no meio da crise — não depois dela.</p><p className="book-hero__description">Com prefácio de Dr. Augusto Cury, a obra parte de uma história real sobre queda, escolhas e reconstrução.</p><div className="book-hero__action"><a className="book-hero__cta" href="#historia">QUERO CONHECER O LIVRO</a><span className="book-hero__microcopy">Livro físico · PDF · EPUB</span></div></div>
        <p className="book-hero__signature">Adilson Borges · Editora Levi</p>
      </section>
      <section className="statement light" id="historia"><div className="wrap"><div className="grid"><div><div className="eyebrow">Uma história escrita durante a queda</div><h2>Não é uma história de sucesso contada <em>depois que tudo deu certo.</em></h2></div><div className="copy">Adilson Borges começou a escrever <em>A Prisão ou o Milhão</em> enquanto ainda tentava reconstruir a própria vida.<br /><br />Não havia um final pronto para transformar em lição. Havia consequências reais, escolhas que precisavam ser encaradas e uma pergunta difícil de ignorar:<div className="question">O que ainda depende de mim a partir daqui?</div><a className="btn" href="#prefacio">Quero ler essa história</a></div></div></div></section>
      <section className="cinema"><img src={CINEMA_DATA} alt="" /><div className="wrap"><blockquote>Algumas histórias são escritas depois da batalha. <strong>Esta começou durante ela.</strong></blockquote></div></section>
      <section className="cury" id="prefacio"><div className="wrap"><div className="grid"><div><div className="eyebrow">Prefácio</div><h2>Uma história que chamou a atenção de Augusto Cury.</h2><div className="body">No prefácio de <em>A Prisão ou o Milhão</em>, Dr. Augusto Cury conduz o leitor para uma das questões centrais da obra: é possível conquistar muito por fora e continuar preso por dentro.</div><div className="quote">“Procurar aquilo que o dinheiro não pode comprar talvez seja a chave que esta obra conduza.”</div><div className="sig">Dr. Augusto Cury · Prefácio de A Prisão ou o Milhão</div></div><div className="portrait"><div className="fallback">AC</div><img className="remote" src="https://portalzumm.com.br/wp-content/uploads/2022/10/Augusto-Cury.jpg" alt="Dr. Augusto Cury" /><div className="portrait-label"><strong>Dr. Augusto Cury</strong><span>Escritor · Prefaciador da obra</span></div></div></div></div></section>
      <section className="identify"><div className="wrap"><div className="top"><div><div className="eyebrow">E onde você entra nessa história?</div><h2>Talvez a sua prisão tenha outro nome.</h2></div><div className="intro">Você não precisa ter vivido a mesma história de Adilson Borges para reconhecer algumas das perguntas que deram origem a este livro.</div></div><div className="cards"><div className="card"><div className="n">01</div><p>Uma decisão que você sabe que precisa tomar — mas continua adiando.</p></div><div className="card"><div className="n">02</div><p>Uma fase da vida que parece durar mais do que deveria.</p></div><div className="card"><div className="n">03</div><p>Um erro que ainda pesa nas escolhas que você faz hoje.</p></div><div className="card"><div className="n">04</div><p>A sensação de que alguma coisa precisa mudar, mesmo sem saber por onde começar.</p></div></div><div className="closing"><h3>A história é de Adilson. <span>Algumas perguntas podem ser suas.</span></h3><a className="btn" href="#top">Quero começar a leitura</a></div></div></section>
    </div>
  )
}
